name = "ExistingProcessManagers"
uuid = "3185f642-0f69-4c32-aed6-948184b6e42b"
authors = ["Dilum Aluthge"]
version = "0.1.0-DEV"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
DocStringExtensions = "0.8"
julia = "1.5"

[extras]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Distributed", "Test"]
